import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JCL Proserve Inc",
  description: "Generated by create next app",
  icons: {
    icon: "/vercel.svg",
    shortcut: "/vercel.svg",
    apple: "/vercel.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster position="top-center" />
        {/* FOOTER - Clean, authoritative layout */}
        <footer className="bg-slate-50 border-t py-20">
          <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12 lg:gap-8">
            <div className="space-y-6">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-lg flex items-center justify-center text-primary-foreground font-bold">
                  <Image
                    src="/jcl-logo.png"
                    alt="Logo"
                    width={40}
                    height={40}
                  />
                </div>
                <span className="font-extrabold text-xl tracking-tight text-black/80">
                  JC&L Proserve Inc.
                </span>
              </div>
              <p className="text-muted-foreground leading-relaxed max-w-xs">
                Setting the global standard in professional staffing and
                manpower management since 2025.
              </p>
            </div>

            <div>
              <h4 className="font-bold text-foreground mb-6 uppercase tracking-widest text-xs">
                Quick Links
              </h4>
              <ul className="space-y-4 text-sm font-medium text-muted-foreground">
                <li>
                  <Link
                    href="/jobs"
                    className="hover:text-primary transition-colors"
                  >
                    Job Openings
                  </Link>
                </li>

                <li>
                  <Link
                    href="/contactus"
                    className="hover:text-primary transition-colors"
                  >
                    Contact Us
                  </Link>
                </li>
              </ul>
            </div>

            <div>
              <h4 className="font-bold text-foreground mb-6 uppercase tracking-widest text-xs">
                Company
              </h4>
              <ul className="space-y-4 text-sm font-medium text-muted-foreground">
                <li>
                  <Link
                    href="/aboutus"
                    className="hover:text-primary transition-colors"
                  >About Us</Link>
                </li>
                <li>
                  <Link
                    href="/services"
                    className="hover:text-primary transition-colors"
                  >Services</Link>
                </li>
              </ul>
            </div>

            <div>
              <h4 className="font-bold text-foreground mb-6 uppercase tracking-widest text-xs">
                Connect
              </h4>
              <div className="space-y-4 text-sm text-muted-foreground">
                <p className="flex items-center gap-2">
                  Unit 203 2nd Floor Landmark Building, Mc. Arthur Highway,
                  Kalayaan Village Service Road, Quebiawan, City of San Fernando
                  Pampanga
                </p>
                <p className="flex items-center gap-2">+63 (993) 190-8150</p>
                <p className="flex items-center gap-2">
                  hr.jclproserve@gmail.com
                </p>
              </div>
            </div>
          </div>
          <div className="max-w-7xl mx-auto px-6 pt-20 mt-20 border-t flex flex-col sm:flex-row justify-between items-center gap-4">
            <p className="text-sm text-muted-foreground font-medium">
              © {new Date().getFullYear()} JC&L Proserve Inc. All rights
              reserved.
            </p>
            <div className="flex gap-6">
              <Link
                href="https://www.facebook.com/jclproserveinc/"
                className="text-xs font-bold text-muted-foreground hover:text-primary uppercase tracking-widest"
              >
                Facebook
              </Link>
              <Link
                href="#"
                className="text-xs font-bold text-muted-foreground hover:text-primary uppercase tracking-widest"
              >
                Tiktok
              </Link>
              <Link
                href="#"
                className="text-xs font-bold text-muted-foreground hover:text-primary uppercase tracking-widest"
              >
                Indeed
              </Link>
              <Link
                href="#"
                className="text-xs font-bold text-muted-foreground hover:text-primary uppercase tracking-widest"
              >
                Jobstreet
              </Link>
              <Link
                href="#"
                className="text-xs font-bold text-muted-foreground hover:text-primary uppercase tracking-widest"
              >
                Linkedin
              </Link>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
